ref_genome: data/hm13.draft_v1.0.fasta                  # Reference genome 
gff: data/chm13.draft_v1.0.gene_annotation.v4.gff3      # Reference genome annotation
vcf: 1KG_CHM13.vcf                                      # Variant call dataset with allele frequencies 
vcf_clinvar: clinvar_liftover_tochm13_v0draft.vcf       # Variant call dataset for additional annotation of filtered variants
af_flag: "AF"                                           # Allele frequency flag in the INFO field to use for the variant filtering
